### ISSUE TITLE
Nimble Writer Crashes on Startup when Symbols are Present in File Names

### ISSUE THREAD

**Issue by Mr-Cyborg** [nimbletools/nimblewriter-beta#8]
**OS: Microsoft® Windows 7 Ultimate 64-bit
Filesystem: NTFS
Origin Hash: ef9bd9bfd8ca4e2561692ed86ef061e946f8b4c6**
### SYNOPSIS

Saving files with symbols (e.g. ™, ©, ®, etc), deleting them and then attempting to open Nimble Writer will throw an MSVC++ Runtime error. This ONLY happens when there is a symbol in the file name. Standard file names are perfectly fine.
### STEPS TO REPRODUCE
1. Start Nimble Writer
2. Save a file using any currently implemented method with a symbol (e.g. ™, ©, ®, etc).
3. Close Nimble Writer
4. Delete the file created during step 2 (make sure to empty recycle bin if you are on Microsoft® Windows)
5. Open Nimble Writer.
### NOTES
- A temporary workaround is to go to "...Steam\userdata<steam3ID>\507160\local\" and delete the config.json file. Then simply launch Nimble Writer and it will automatically generate a new one.
  - You can find your steam3ID by first going to your Steam profile (preferably in your web browser) and copying the number after profiles/ in the url. Then go to steamrep.com and enter that number into the search field. From there, under your avatar you'll find a list of numbers. Look for the Steam3ID and that should correspond to the directory you find in your userdata folder.
- This issue has only been reproduced with files whose name contains symbols.
### RESOURCES

![ef9bd9bfd8ca4e2561692ed86ef061e946f8b4c6-issue-8-msvc -runtime-error](https://cloud.githubusercontent.com/assets/21320349/18258988/d3cd8952-73a4-11e6-897a-1ccb3918fa60.png)

**Comment by Mr-Cyborg** [comment]
**ADDENDUM 2016-09-08T09:29:20UTC
OS: Solus 64-bit, Microsoft® Windows 7 Ultimate 64-bit
Filesystem: EXT4, NTFS
Version Hash: ef9bd9bfd8ca4e2561692ed86ef061e946f8b4c6**

### SYNOPSIS

Deleting files whose names contain a symbol (e.g. ™, ©, ®, etc) results in a crash on start up. More specifically on Windows, MSVC++ Runtime will throw a generic error while UNIX (namely while using EXT4) will simply crash without any direct feedback.

### STEPS TO REPRODUCE
1. Start Nimble Writer
2. Save a file using any currently implemented method with a symbol (e.g. ™, ©, ®, etc).
3. Close Nimble Writer.
4. Delete the file created during step 2 (make sure to empty recycle bin if you are on Microsoft® Windows)
5. Open Nimble Writer.

### NOTES
- A temporary workaround is to delete the user config.json file found in the following directories:
  - UNIX: "/home/host username/.local/share/steam/userdata/<steam3ID/507160/local/"
    - You may have to enter root in order to access the .local directory since most distros hide this directory by default. Your file manager may also have a setting that allows you to view hidden directories.
  - Microsoft® Windows: "...\steam\userdata<steam3ID>\507160\local\"
  - You can find your steam3ID by first going to your Steam profile (preferably in your web browser) and copying the number after profiles/ in the url. Then go to steamrep.com and enter that number into the search field. From there, under your avatar you'll find a list of numbers. Look for the Steam3ID and that should correspond to the directory you find in your userdata folder.
- This issue has only been reproduced with files whose name contains symbols.

**Comment by codecat** [comment]
Should be solved in the next patch.
